### ISSUE TITLE
[Docs]: Not public link, see https://confluence.iguazeng.com/display/FC/Kafka%3A+deployment+in+2+minutes

### ISSUE THREAD

**Issue by george0st** [mlrun/test-notebooks#96]
Not public link, see url https://github.com/mlrun/test-notebooks/blob/main/kafka_redis_fs/fs-kafka-redis.ipynb

It contains sentence with link "Create a kafka service named my-kafka on default-tenant namespace - you can use this confluent document [link](https://confluence.iguazeng.com/display/FC/Kafka%3A+deployment+in+2+minutes)"

It will be fine to remove link or move content to the public URL.

**Comment by MichaelSkralivetsky** [comment]
https://github.com/mlrun/test-notebooks/commit/e69b43e0d125751eb82fe2aff4c7db4772da3765
